### PR TITLE
Create es_es.json

### PR DESCRIPTION
**Pull request by albertosaurio65**

### CODE REVIEW

**Comment by albertosaurio65** [comment]
Exist any problem?

**Comment by Dark-Arcana** [comment]
This may take some time to review. Thanks for working on it!

**Comment by Dark-Arcana** [comment]
I was going to merge this after reviewing, but your branch is not up to date. It's 18 commits behind. Instead I will close this but copy over your provided file to prevent any issues.

**Comment by Dark-Arcana** [comment]
Upon further inspection, there are too many missing entries and Spanish is not my primary language, so I can't fix it. Please create an entirely new branch from the most up to date copy of 1.18.x and add your translations back in. Thank you.

**Pull request closed without merging**
